// Generated by https://quicktype.io

export interface APIPokemons {
  count:    number;
  next:     string;
  previous: null;
  results:  Pokemon[];
}

export interface Pokemon {
  name: string;
  url:  string;
}
